version: "3"
services:
    app:
        build: .
        ports:
            - "8000:80"
        depends_on:
            - db
        volumes:
            - .:/code/app
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
    db:
        image: "microsoft/mssql-server-linux:2017-latest"
        environment:
            SA_PASSWORD: "Supersecret1234"
            ACCEPT_EULA: "Y"